export const CART_ACTIONS_TYPE = {
  SET_CART_ITEM: "cart/SET_CART_ITEM",
  SET_CART_IS_OPEN: "cart/SET_CART_IS_OPEN",
  REMOVE_CART_ITEM: "cart/REMOVE_CART_ITEM",
  CLEAR_CART_ITEMS: "cart/CLEAR_CART_ITEMS",
  TOTAL_CART_ITEMS: "cart/TOTAL_CART_ITEMS",
  COUNT_CART_ITEMS: "cart/COUNT_CART_ITEMS",
};
